#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

# Start a local dbus daemon (TEST)
#if ! pgrep -f "dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus"
#then	
#	dbus-daemon --session --address=unix:path="$XDG_RUNTIME_DIR"/bus 2>&1 |
#       		"$STARTW_ROOT"/addts >> "$STARTW_LOG_FILE" &
#fi

# Load .Xresources
[ -f ~/.Xresources ] && xrdb -merge -I $HOME ~/.Xresources

# Load ~/.config/x11/xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.config/x11/xprofile"
fi

dbus-launch --exit-with-session dwm
